name: Publish NuGet Packages

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
        description: "The version of the packages."
      use-nuget:
        type: boolean
        required: false
        default: true
        description: "Whether to push to the NuGet registry. Requires a valid NUGET_API_KEY."
      use-github:
        type: boolean
        required: false
        default: false
        description: "Whether to push to the GitHub Package registry."
    secrets:
      NUGET_API_KEY:
        required: true
        description: "A valid NuGet API key. Required when pushing to NuGet."

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Setup .NET Core SDK 9.0.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          include-prerelease: true

      - name: Setup .NET Core SDK 8.0.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          include-prerelease: true          

      - name: Print debug info
        run: dotnet --info

      - name: Pack
        run: dotnet pack -c Release -p:Version="${{ inputs.version }}" -p:RepositoryBranch=${{ github.ref_name }} -p:RepositoryCommit="${{ github.sha }}"

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: nuget-packages-${{ inputs.version }}
          path: |
            **/*.nupkg
            **/*.snupkg
          if-no-files-found: error

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: nuget-packages-${{ inputs.version }}

      - name: Push to NuGet
        if: inputs.use-nuget
        run: dotnet nuget push **/*.nupkg --skip-duplicate --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json

      - name: Push to GitHub
        if: inputs.use-github
        run: dotnet nuget push **/*.nupkg --skip-duplicate --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
