# This is not reusable, this runs on the meta-repo itself.
name: Test .NET build and test

on:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/dotnet-build-and-test.yaml"
      - ".github/workflows/test-dotnet-build-and-test.yaml"
      - "test-files/**"
  pull_request:
    branches: [ main ]
    paths:
      - ".github/workflows/dotnet-build-and-test.yaml"
      - ".github/workflows/test-dotnet-build-and-test.yaml"
      - "test-files/**"

jobs:
  run-test:
    uses: Nexus-Mods/NexusMods.App.Meta/.github/workflows/dotnet-build-and-test.yaml@780d2001be902a9523de8331da2c77c687abbddb
    with:
      project-file: "test-files/DummyTest/DummyTest.csproj"
      use-codecov: false
